### PR TITLE
Moving example one level deeper to static subfolder

### PR DESCRIPTION
**Pull request by applikationsprogramvara**
### !!! Please do not merge the pull request !!!
Read my comment below.

Here is a preparation for updating the readme quick start, which will be partially based on the comment https://github.com/caressofsteel/hugo-story/issues/4#issuecomment-695212385 .

Also I'm planning to do some cleaning inside the static folder, which is looking heavy for me. What do you think about it?

### CODE REVIEW

**Comment by applikationsprogramvara** [comment]
Please do not merge this PR! 

I need to rethink the idea. 
It looks like the `exampleSite` is not needed at all. Point 3 from https://github.com/caressofsteel/hugo-story/issues/4#issuecomment-695212385 is for sure confusing.

What for `exampleSite`  is needed?

**Comment by caressofsteel** [comment]
"examplesite" is the output of  a successful build used to preview the theme and its functions. I think it's cool to have so someone can preview the theme and verify original functionality without having Hugo. Ideally, it should be replaced with the output generated with the recent commits.

**Comment by applikationsprogramvara** [comment]
Thank you for the explanation! It was not clear, that `exampleSite` is the original Story example.

Actually I saw in some other themes, where under `exampleSite` the folders for the main hugo site were replicated, so you can kick start development of your site by simply copying these folders and config to the root of the main site. This knowledge together with the comment https://github.com/caressofsteel/hugo-story/issues/4#issuecomment-695212385 fit together, but does not fit the idea of the original or generated site.

So here are is my suggestion: let's rename `exampleSite` to `originalStorySite`.

I tend to keep `exampleSite/data` subfolder which I created in PRs https://github.com/caressofsteel/hugo-story/pull/6 and https://github.com/caressofsteel/hugo-story/pull/7. 
_This contradicts my previous comment https://github.com/caressofsteel/hugo-story/pull/8#issuecomment-771140216, but after some experiments, I understood, that keeping `data` in the root of the theme will always overwrite all user main site adjustments, which is not always needed_

I would also keep a default `exampleSite/config.toml`, so it would be easier for the developer to apply the theme.

If you are OK with that, I will close the current PR and will come back with suggested changes.

**Comment by caressofsteel** [comment]
No problem. It's been a while since I've looked over the project, or Hugo for that matter. Your proposed changes sound fine. I just saw another user is liking the updates and requested some other feature. Thanks again for the effort. It is appreciated by myself and many others I'm sure.
-cos

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request closed without merging**
